### ISSUE TITLE
Cant find redis store

### ISSUE THREAD

**Issue by webartistse** [markap/socket.io-scale#3]
module.js:340
    throw err;
          ^
Error: Cannot find module 'socket.io/lib/stores/redis'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/johan/Apps/socket.io-scale/server.js:16:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by pineli** [comment]
i was with this problem... do you need to do it
var io = require('socket.io')(server);
var redis = require('socket.io-redis');
io.adapter(redis({ host: 'localhost', port: 6379 }));
